### ISSUE TITLE
Correção de Artefatos

### ISSUE THREAD

**Issue by Natilorens** [fga-eps-mds/2022-1-CAPJu-Doc#128]
## Descrição

Realizar a correção de alguns artefatos de documentação de acordo com o feedback da R1. 

## Tarefas
- [x] Correção do documento de Riscos
- [ ] Correção do  documento de Qualidade
- [x] Correção do  documento de Arquitetura
- [x] Correção do Guia de Contribuição
- [x] Correção do documentação de Custos

**Comment by FranciscoHeronildo** [comment]
Foram feitas atualizações no documento de arquitetura e já encontra-se na devel, mas está faltando o diagrama que representa os dados.
