### ISSUE TITLE
Treinamento - Desenvolvimento Web

### ISSUE THREAD

**Issue by FranciscoHeronildo** [fga-eps-mds/2022-1-CAPJu-Doc#13]
## Descrição
Treinamento sobre o básico do desenvolvimento WEB incluindo HTML, CSS e javascript que é a base de conhecimento necessária para utilizar frameworks como React.

**Comment by MaiconMares** [comment]
# Conteúdo abordado
O treinamento teve como foco o ensinamento dos principais conceitos de HTML, incluindo as `tags` mais utilizadas, a separação de camadas da web (HTML, CSS e JS em arquivos separados) na composição de um documento HTML, principais seletores e regras CSS, principais recursos do Javascript e recursos modernos do ECMAScript6. Também foram mencionados sites úteis para a busca de conteúdo para estudo ([W3 Schools](https://www.w3schools.com/)).
## Principais tags HTML abordadas
```bash
- Listas: <ul></ul> e <ol></ol>
- Títulos: <h1> a <h6>
- Textos: <p>, <span>, <strong>, etc
- Mídia/recursos externos: <img>, <link>, <script>
- Formulário: <form>, <input>, <label>
- Botões de ação/link: <button>, <a>, <submit>
- Seletores: class e id
```

## CSS
- border
- display
- Flexbox/posicionamento/responsividade
- color
- background
- font-family, font-size, etc
- seletores
- margin
- padding

## Javascript
- Tipos de dados
- Funções
- Como fazer requisições 
- async e await (assincronicidade de eventos)
- Promises
- Template Literals
- Objetos
- Principais métodos para lidar com arrays (reduce, map, filter, forEach, etc)

# Material
O vídeo completo do treinamento pode ser encontrado em: [Assistir]().

# Participantes
Francisco Heronildo, Maicon Mares, Hellen Fernanda, Lucas Lopes, Gabriel Araujo. Obs.: Adicionar o resto dos participantes.
