### ISSUE TITLE
Orquestração das Pipelines

### ISSUE THREAD

**Issue by FranciscoHeronildo** [fga-eps-mds/2022-1-CAPJu-Doc#32]
## Descrição
Criação de Pipelines para automação de processos DevOps

## Tarefas
- [x] Configuração de Validação de Lint
- [x] Chamada de api para o sonarcloud

## Critérios de Aceitação
- [x] Pipelines integradas aos dois repositórios de códigos com configuração de Lint, execução de testes e geração de métricas

**Comment by aquiles23** [comment]
mesma coisa que a issue #43

**Comment by aquiles23** [comment]
reaberto pois também vai ser utilizado github actions
