### ISSUE TITLE
US[05] - Manter Perfis de Acesso

### ISSUE THREAD

**Issue by aquiles23** [fga-eps-mds/2022-1-CAPJu-Doc#75]
## Descrição

Eu como Diretor desejo delegar perfis de acesso para definir os níveis de acesso dos usuários com o sistema e deletar um usuário do sistema.
Obs: Seguir as páginas [perfis de Acesso](https://www.figma.com/file/mIuWiz0i0f6asi8jNpBNn4/CAPJu---Perfis-de-Acesso), conforme o protótipo de alta fidelidade.

## Tarefas

- [x] Adicionar à barra lateral o ícone para Perfis de Acesso segundo o Protótipo de Alta Fidelidade.
- [x] Desenvolver `endpoint` no backend para registro dos perfis de acesso.
- [x] Não permitir cadastrar/editar um perfil em branco.
- [x] Implementar `dropdown` com os perfis de acesso disponíveis na aplicação para delegá-los ao usuário.
- [x] Implementar os perfis de acesso:  Diretor, servidor, estagiário e juiz.
- [x] Implementar `modal` para alterar o perfil de acesso  de um usuário.
- [x] Implementar `modal` para deletar um usuário.
- [x] Mostrar mensagem informando que o usuário foi removido com sucesso e atualizar a tela com os usuários disponíveis.
- [x] Implementar tela pra listar todos os usuários.
- [x] Criar filtro na tela de listagem de usúarios.
- [x] Seguir protótipo de Alta fidelidade e a identidade visual.
- [ ] Fazer testes de integração e unitário.

## Critérios de aceitação

- [ ] Somente o diretor deve ser capaz de delegar os perfis de acesso.
- [ ] Cada usuário deve apenas ser capaz de usar as funcionalidades do sistema que correpondem as permissões de seu perfil de acesso. 
- [ ] Somente o diretor poder deletar um usuário.
- [ ] Ser possível filtrar os usuários na tela que mostra todos os usuários.

## Dependência

- [ ] F[02]US[04]

Issues necessárias para a continuidade ou conclusão desta Issue

**Comment by Natilorens** [comment]
@PhilipeSousa e @PabloChristianno, está sendo possível deletar o usuário que está logado. 
Ao buscar um usuário deve ser possível buscar independentemente de estar em caixa alta.
