### ISSUE TITLE
F[04]US[17] - definir o fluxo ao qual um processo está atrelado

### ISSUE THREAD

**Issue by aquiles23** [fga-eps-mds/2022-1-CAPJu-Doc#81]
## Descrição

Eu como Usuário desejo definir o fluxo ao qual um processo está atrelado para  saber qual sequência de status este processo tem

## Tarefas

- [ ] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

## Critérios de aceitação

- [ ] Critério 1
- [ ] Critério 2
- [ ] Critério 3

## Dependência

Issues necessárias para a continuidade ou conclusão desta Issue

- [ ] Issue necessária 1
- [ ] Issue necessária 2

**Comment by MaiconMares** [comment]
@Natilorens @ArthurPaivaT após novos pedidos do Wellington essa história não se faz mais necessária!
